# ===============================
# = JPA / HIBERNATE
# ===============================
# Show or not log for each sql query
spring:
  datasource:
    url: jdbc:derby:db_inventory
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      properties:
        hibernate.dialect: org.hibernate.dialect.DerbyDialect
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy

          #implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
          #phsyical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 6969

# Hibernate ddl auto (create, create-drop, update): with "create-drop" the database
# schema will be automatically created afresh for every start of application

# Allows Hibernate to generate SQL optimized for a particular DBMS
